import AppKit
import ProtonXCore

@MainActor
final class ClipboardController {
    static let shared = ClipboardController()
    private var lease: ClipboardLease?
    private var task: Task<Void, Never>?
    func copy(_ text: String) {
        task?.cancel()
        let board = NSPasteboard.general
        board.clearContents()
        board.setString(text, forType: .string)
        // Universal Clipboard and third-party history managers are asked to exclude the content.
        board.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        board.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        board.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        lease = ClipboardLease(changeCount: board.changeCount)
        task = Task { try? await Task.sleep(for: .seconds(30)); if !Task.isCancelled { clearOwned() } }
    }
    func clearOwned() {
        task?.cancel(); task = nil
        if lease?.owns(currentChangeCount: NSPasteboard.general.changeCount) == true { NSPasteboard.general.clearContents() }
        lease = nil
    }
}
